//! 타입 폴더별 `_index.md` 자동 생성.
//! 완전 자동 생성 파일 — 내용이 같으면 쓰기를 생략해 감시/미러 루프를 막는다.

use std::fs;

use crate::error::CoreError;
use crate::schema::{Builtin, BOOK_STATUSES};
use crate::vault::{NoteSummary, Vault};

const MARKER: &str = "<!-- generated by YamchaMemo — 직접 수정하지 마세요 -->";

pub fn update_index(vault: &Vault, type_id: &str) -> Result<(), CoreError> {
    let Some(def) = vault.def_by_id(type_id) else {
        return Ok(());
    };
    let label = def.label.clone();
    let folder = def.folder.clone();
    let notes: Vec<NoteSummary> = vault
        .list_notes()?
        .into_iter()
        .filter(|n| n.note_type == type_id)
        .collect();
    let content = render(type_id, &label, &notes);
    let path = vault.root().join(&folder).join("_index.md");
    if let Ok(existing) = fs::read_to_string(&path) {
        if existing == content {
            return Ok(());
        }
    }
    fs::write(&path, content)?;
    Ok(())
}

fn stem(n: &NoteSummary) -> String {
    n.rel_path
        .rsplit('/')
        .next()
        .unwrap_or(&n.rel_path)
        .trim_end_matches(".md")
        .to_string()
}

fn fm_str<'a>(n: &'a NoteSummary, key: &str) -> &'a str {
    n.frontmatter.get(key).and_then(|v| v.as_str()).unwrap_or("")
}

fn status_label(status: &str) -> &str {
    BOOK_STATUSES
        .iter()
        .find(|(v, _)| *v == status)
        .map(|(_, l)| *l)
        .unwrap_or(status)
}

fn render(type_id: &str, label: &str, notes: &[NoteSummary]) -> String {
    let mut out = format!("{MARKER}\n# {label} 목록\n\n총 {}개\n\n", notes.len());
    match Builtin::from_id(type_id) {
        Some(Builtin::Book) => render_books(&mut out, notes),
        Some(Builtin::Daily) => render_by_month(&mut out, notes),
        _ => render_date_list(&mut out, notes),
    }
    out
}

/// Books: 분야별 섹션 × 표(제목/저자/상태/평점/기록수)
fn render_books(out: &mut String, notes: &[NoteSummary]) {
    let mut genres: Vec<String> = Vec::new();
    for n in notes {
        let g = match fm_str(n, "genre") {
            "" => "미분류".to_string(),
            g => g.to_string(),
        };
        if !genres.contains(&g) {
            genres.push(g);
        }
    }
    genres.sort();

    for genre in genres {
        out.push_str(&format!("## {genre}\n\n"));
        out.push_str("| 제목 | 저자 | 상태 | 평점 | 기록 |\n");
        out.push_str("| --- | --- | --- | --- | --- |\n");
        for n in notes {
            let g = match fm_str(n, "genre") {
                "" => "미분류",
                g => g,
            };
            if g != genre {
                continue;
            }
            let author = fm_str(n, "author");
            let rating = n
                .frontmatter
                .get("rating")
                .and_then(|v| v.as_f64())
                .map(|r| format!("{r}"))
                .unwrap_or_default();
            let records = if n.entry_count > 0 {
                format!("{}개", n.entry_count)
            } else {
                String::new()
            };
            out.push_str(&format!(
                "| [[{}]] | {} | {} | {} | {} |\n",
                stem(n),
                author,
                status_label(fm_str(n, "status")),
                rating,
                records,
            ));
        }
        out.push('\n');
    }
}

/// Daily: 월별 섹션, 날짜 역순
fn render_by_month(out: &mut String, notes: &[NoteSummary]) {
    let mut month = String::new();
    for n in notes {
        let m = n.date.get(..7).unwrap_or("기타").to_string();
        if m != month {
            out.push_str(&format!("## {m}\n\n"));
            month = m;
        }
        out.push_str(&format!("- [[{}]]\n", stem(n)));
    }
    out.push('\n');
}

/// 기타 타입: 날짜 역순 목록
fn render_date_list(out: &mut String, notes: &[NoteSummary]) {
    for n in notes {
        if n.date.is_empty() {
            out.push_str(&format!("- [[{}]]\n", stem(n)));
        } else {
            out.push_str(&format!("- {} [[{}]]\n", n.date, stem(n)));
        }
    }
    out.push('\n');
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn vault() -> (tempfile::TempDir, Vault) {
        let dir = tempfile::tempdir().unwrap();
        let v = Vault::open(dir.path()).unwrap();
        (dir, v)
    }

    #[test]
    fn book_index_grouped_by_genre() {
        let (_d, v) = vault();
        v.create_note(
            "book",
            "클린 코드",
            json!({"author": "로버트 마틴", "genre": "개발"}),
        )
        .unwrap();
        v.create_note("book", "노르웨이의 숲", json!({"genre": "소설"}))
            .unwrap();
        update_index(&v, "book").unwrap();
        let idx = fs::read_to_string(v.root().join("Books/_index.md")).unwrap();
        assert!(idx.starts_with(MARKER));
        assert!(idx.contains("## 개발"));
        assert!(idx.contains("## 소설"));
        assert!(idx.contains("[[클린 코드]]"));
        assert!(idx.contains("읽고 싶은 책"));
    }

    #[test]
    fn unchanged_content_skips_write() {
        let (_d, v) = vault();
        v.create_note("free", "메모", json!({})).unwrap();
        update_index(&v, "free").unwrap();
        let path = v.root().join("Free/_index.md");
        let mtime1 = fs::metadata(&path).unwrap().modified().unwrap();
        update_index(&v, "free").unwrap();
        let mtime2 = fs::metadata(&path).unwrap().modified().unwrap();
        assert_eq!(mtime1, mtime2);
    }

    #[test]
    fn daily_index_by_month() {
        let (_d, v) = vault();
        v.open_daily("2026-07-18").unwrap();
        v.open_daily("2026-06-01").unwrap();
        update_index(&v, "daily").unwrap();
        let idx = fs::read_to_string(v.root().join("Daily/_index.md")).unwrap();
        assert!(idx.contains("## 2026-07"));
        assert!(idx.contains("## 2026-06"));
        assert!(idx.contains("- [[2026-07-18]]"));
    }
}
