//! 타입 폴더별 `_index.md` 자동 생성.
//! 완전 자동 생성 파일 — 내용이 같으면 쓰기를 생략해 감시/미러 루프를 막는다.

use std::fs;

use crate::error::CoreError;
use crate::schema::{Builtin, BOOK_STATUSES};
use crate::vault::{NoteSummary, Vault};

const MARKER: &str = "<!-- generated by YamchaMemo — 직접 수정하지 마세요 -->";

pub fn update_index(vault: &Vault, type_id: &str) -> Result<(), CoreError> {
    let Some(def) = vault.def_by_id(type_id) else {
        return Ok(());
    };
    let label = def.label.clone();
    let folder = def.folder.clone();
    // 이 타입의 폴더만 읽는다 — 전체를 읽고 걸러내면 나머지 폴더까지 파싱하는 값을 치른다
    let notes: Vec<NoteSummary> = vault.list_notes_of_type(type_id)?;
    let content = render(type_id, &label, &notes);
    let path = vault.root().join(&folder).join("_index.md");
    if let Ok(existing) = fs::read_to_string(&path) {
        if existing == content {
            return Ok(());
        }
    }
    fs::write(&path, content)?;
    Ok(())
}

fn stem(n: &NoteSummary) -> String {
    n.rel_path
        .rsplit('/')
        .next()
        .unwrap_or(&n.rel_path)
        .trim_end_matches(".md")
        .to_string()
}

fn fm_str<'a>(n: &'a NoteSummary, key: &str) -> &'a str {
    n.frontmatter.get(key).and_then(|v| v.as_str()).unwrap_or("")
}

fn status_label(status: &str) -> &str {
    BOOK_STATUSES
        .iter()
        .find(|(v, _)| *v == status)
        .map(|(_, l)| *l)
        .unwrap_or(status)
}

fn render(type_id: &str, label: &str, notes: &[NoteSummary]) -> String {
    let mut out = format!("{MARKER}\n# {label} 목록\n\n총 {}개\n\n", notes.len());
    match Builtin::from_id(type_id) {
        Some(Builtin::Book) => render_books(&mut out, notes),
        Some(Builtin::Daily) => render_by_month(&mut out, notes),
        _ => render_date_list(&mut out, notes),
    }
    out
}

/// Books: 분야별 섹션 × 표(제목/저자/상태/평점/기록수)
fn render_books(out: &mut String, notes: &[NoteSummary]) {
    let mut genres: Vec<String> = Vec::new();
    for n in notes {
        let g = match fm_str(n, "genre") {
            "" => "미분류".to_string(),
            g => g.to_string(),
        };
        if !genres.contains(&g) {
            genres.push(g);
        }
    }
    genres.sort();

    for genre in genres {
        out.push_str(&format!("## {genre}\n\n"));
        out.push_str("| 제목 | 저자 | 상태 | 평점 | 기록 |\n");
        out.push_str("| --- | --- | --- | --- | --- |\n");
        for n in notes {
            let g = match fm_str(n, "genre") {
                "" => "미분류",
                g => g,
            };
            if g != genre {
                continue;
            }
            let author = fm_str(n, "author");
            let rating = n
                .frontmatter
                .get("rating")
                .and_then(|v| v.as_f64())
                .map(|r| format!("{r}"))
                .unwrap_or_default();
            let records = if n.entry_count > 0 {
                format!("{}개", n.entry_count)
            } else {
                String::new()
            };
            out.push_str(&format!(
                "| [[{}]] | {} | {} | {} | {} |\n",
                stem(n),
                author,
                status_label(fm_str(n, "status")),
                rating,
                records,
            ));
        }
        out.push('\n');
    }
}

/// Daily: 월별 섹션, 날짜 역순
fn render_by_month(out: &mut String, notes: &[NoteSummary]) {
    let mut month = String::new();
    for n in notes {
        let m = n.date.get(..7).unwrap_or("기타").to_string();
        if m != month {
            out.push_str(&format!("## {m}\n\n"));
            month = m;
        }
        out.push_str(&format!("- [[{}]]\n", stem(n)));
    }
    out.push('\n');
}

/// 기타 타입: 날짜 역순 목록
fn render_date_list(out: &mut String, notes: &[NoteSummary]) {
    for n in notes {
        if n.date.is_empty() {
            out.push_str(&format!("- [[{}]]\n", stem(n)));
        } else {
            out.push_str(&format!("- {} [[{}]]\n", n.date, stem(n)));
        }
    }
    out.push('\n');
}

#[cfg(test)]
mod deferred_tests {
    use crate::Vault;
    use serde_json::json;

    /// 저장은 목록 파일을 만들지 않고 표시만 한다 — 그래야 저장이 O(1)로 끝난다.
    /// 대신 flush를 부르면 반드시 반영돼야 한다. 이 계약이 깨지면 `_index.md`가
    /// 영원히 낡은 채로 남는다.
    #[test]
    fn 저장은_표시만_하고_flush가_반영한다() {
        let d = tempfile::tempdir().unwrap();
        let v = Vault::open(d.path()).unwrap();
        let index = d.path().join("Free").join("_index.md");

        let rel = v.create_note("free", "첫 노트", json!({})).unwrap();
        v.save_note(&rel, json!({}), "본문").unwrap();

        // 아직 만들어지지 않았다 (만들어졌다면 저장 경로가 vault를 다 읽고 있다는 뜻)
        assert!(v.has_stale_index(), "낡음 표시가 없다");

        assert_eq!(v.flush_index_files().unwrap(), 1);
        assert!(!v.has_stale_index(), "flush 뒤에도 표시가 남았다");
        let text = std::fs::read_to_string(&index).unwrap();
        assert!(text.contains("첫 노트"), "목록에 노트가 없다: {text}");

        // 두 번째 flush는 할 일이 없다 (같은 일을 반복하지 않는다)
        assert_eq!(v.flush_index_files().unwrap(), 0);
    }

    /// 여러 번 저장해도 flush 한 번이면 된다 — 자동저장이 3초마다 도는 앱이라
    /// 여기서 쌓이면 그대로 비용이 된다.
    #[test]
    fn 여러_번_저장해도_한_번만_만든다() {
        let d = tempfile::tempdir().unwrap();
        let v = Vault::open(d.path()).unwrap();
        let rel = v.create_note("free", "노트", json!({})).unwrap();
        for i in 0..20 {
            v.save_note(&rel, json!({}), &format!("{i}번째")).unwrap();
        }
        // free 타입 하나뿐 — 20번 저장했어도 만들 목록은 하나다
        assert_eq!(v.flush_index_files().unwrap(), 1);
    }

    /// 삭제도 목록에 반영돼야 한다 (표시 대상이 지운 노트의 타입이어야 한다)
    #[test]
    fn 삭제도_반영된다() {
        let d = tempfile::tempdir().unwrap();
        let v = Vault::open(d.path()).unwrap();
        let rel = v.create_note("free", "지울 노트", json!({})).unwrap();
        v.flush_index_files().unwrap();
        assert!(std::fs::read_to_string(d.path().join("Free/_index.md"))
            .unwrap()
            .contains("지울 노트"));

        v.delete_note(&rel).unwrap();
        v.flush_index_files().unwrap();
        assert!(!std::fs::read_to_string(d.path().join("Free/_index.md"))
            .unwrap()
            .contains("지울 노트"));
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn vault() -> (tempfile::TempDir, Vault) {
        let dir = tempfile::tempdir().unwrap();
        let v = Vault::open(dir.path()).unwrap();
        (dir, v)
    }

    #[test]
    fn book_index_grouped_by_genre() {
        let (_d, v) = vault();
        v.create_note(
            "book",
            "클린 코드",
            json!({"author": "로버트 마틴", "genre": "개발"}),
        )
        .unwrap();
        v.create_note("book", "노르웨이의 숲", json!({"genre": "소설"}))
            .unwrap();
        update_index(&v, "book").unwrap();
        let idx = fs::read_to_string(v.root().join("Books/_index.md")).unwrap();
        assert!(idx.starts_with(MARKER));
        assert!(idx.contains("## 개발"));
        assert!(idx.contains("## 소설"));
        assert!(idx.contains("[[클린 코드]]"));
        assert!(idx.contains("읽고 싶은 책"));
    }

    #[test]
    fn unchanged_content_skips_write() {
        let (_d, v) = vault();
        v.create_note("free", "메모", json!({})).unwrap();
        update_index(&v, "free").unwrap();
        let path = v.root().join("Free/_index.md");
        let mtime1 = fs::metadata(&path).unwrap().modified().unwrap();
        update_index(&v, "free").unwrap();
        let mtime2 = fs::metadata(&path).unwrap().modified().unwrap();
        assert_eq!(mtime1, mtime2);
    }

    #[test]
    fn daily_index_by_month() {
        let (_d, v) = vault();
        v.open_daily("2026-07-18").unwrap();
        v.open_daily("2026-06-01").unwrap();
        update_index(&v, "daily").unwrap();
        let idx = fs::read_to_string(v.root().join("Daily/_index.md")).unwrap();
        assert!(idx.contains("## 2026-07"));
        assert!(idx.contains("## 2026-06"));
        assert!(idx.contains("- [[2026-07-18]]"));
    }
}
