// @ts-nocheck
/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async coreVersion() : Promise<string> {
    return await TAURI_INVOKE("core_version");
},
/**
 * vault 폴더를 열고 (없으면 폴더 구조 생성) 전체 재색인
 */
async setVault(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_vault", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 존재하는 클라우드 동기화 폴더를 감지해 제안 목록으로 반환한다.
 * 마지막 항목은 항상 문서 폴더. 없는 경로는 건너뛴다.
 */
async detectStorageDirs() : Promise<StorageDir[]> {
    return await TAURI_INVOKE("detect_storage_dirs");
},
async getVaultPath() : Promise<string | null> {
    return await TAURI_INVOKE("get_vault_path");
},
/**
 * 타입 정의 목록 (내장 + 사용자 정의). vault가 없으면 내장만.
 */
async getSchemas() : Promise<TypeDef[]> {
    return await TAURI_INVOKE("get_schemas");
},
async listNotes() : Promise<Result<NoteSummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_notes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readNote(relPath: string) : Promise<Result<NoteContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_note", { relPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveNote(relPath: string, frontmatter: JsonValue, body: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_note", { relPath, frontmatter, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 노트 생성 → 생성된 rel 경로 반환
 */
async createNote(noteType: string, title: string, fields: JsonValue) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_note", { noteType, title, fields }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteNote(relPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_note", { relPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 오늘의 데일리노트 열기 (없으면 생성)
 */
async openTodayDaily() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_today_daily") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 특정 날짜의 데일리노트 열기 (없으면 생성)
 */
async openDaily(date: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_daily", { date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 내보내기 파일 쓰기 — 사용자가 저장 대화상자에서 고른 경로에 그대로 쓴다.
 * (vault 밖이어도 된다. 사용자가 직접 고른 자리이므로)
 */
async writeExport(path: string, contents: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_export", { path, contents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 책 노트 → 연결된 독서기록 찾기/생성
 */
async readingForBook(bookRelPath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reading_for_book", { bookRelPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 독서기록에 엔트리 추가 → 갱신된 노트 반환
 */
async appendReadingEntry(relPath: string, kind: EntryKind, text: string) : Promise<Result<NoteContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("append_reading_entry", { relPath, kind, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 데일리노트 빠른 입력 (할 일/기록/느낌) → 갱신된 노트 반환
 */
async appendDailyEntry(relPath: string, kind: DailyKind, text: string) : Promise<Result<NoteContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("append_daily_entry", { relPath, kind, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 보기 화면용 블록 목록.
 * `## 기록`은 콜아웃/원문을 순서대로, 그 밖의 섹션은 원문 블록으로 덧붙인다 —
 * 화면이 파일 내용을 조용히 숨기지 않도록.
 */
async noteBlocks(relPath: string) : Promise<Result<NoteBlock[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("note_blocks", { relPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 항목 종류 변경. `source`는 "entry"(기록 콜아웃) 또는 "todo".
 * `new_kind`가 "할 일"이면 체크박스로 바뀌며 섹션도 함께 옮겨진다.
 */
async changeKind(relPath: string, source: string, index: number, expectedText: string, newKind: string) : Promise<Result<NoteContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_kind", { relPath, source, index, expectedText, newKind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 사용자 정의 종류로 기록 추가 → 갱신된 노트
 */
async appendCallout(relPath: string, label: string, text: string) : Promise<Result<NoteContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("append_callout", { relPath, label, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * vault에 저장된 사용자 정의 콜아웃 목록
 */
async listCallouts() : Promise<Result<CalloutDef[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_callouts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 사용자 정의 콜아웃 추가 → 갱신된 목록
 */
async addCallout(def: CalloutDef) : Promise<Result<CalloutDef[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_callout", { def }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 사용자 정의 콜아웃 제거 → 갱신된 목록 (이미 쓴 노트 내용은 건드리지 않는다)
 */
async removeCallout(label: string) : Promise<Result<CalloutDef[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_callout", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 일지의 할 일 목록 (`## 할 일` 섹션, 없으면 본문 전체). 완료·미완료 모두.
 */
async noteTodos(relPath: string) : Promise<Result<NoteTodo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("note_todos", { relPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 할 일 완료 여부 토글 → 갱신된 노트
 */
async toggleTodo(relPath: string, index: number, expectedText: string, done: boolean) : Promise<Result<NoteContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_todo", { relPath, index, expectedText, done }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 할 일 내용 수정 (완료 여부 유지) → 갱신된 노트
 */
async updateTodo(relPath: string, index: number, expectedText: string, newText: string) : Promise<Result<NoteContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_todo", { relPath, index, expectedText, newText }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 할 일 삭제 → 갱신된 노트
 */
async deleteTodo(relPath: string, index: number, expectedText: string) : Promise<Result<NoteContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_todo", { relPath, index, expectedText }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 기록 콜아웃 한 건의 본문 수정 (종류·날짜 유지) → 갱신된 노트.
 * `expected_text`는 화면에서 보던 내용 — 그 사이 파일이 바뀌었으면 거부한다.
 */
async updateEntry(relPath: string, index: number, expectedText: string, newText: string) : Promise<Result<NoteContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_entry", { relPath, index, expectedText, newText }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 기록 콜아웃 한 건 삭제 → 갱신된 노트. `expected_text`가 다르면 거부한다.
 */
async deleteEntry(relPath: string, index: number, expectedText: string) : Promise<Result<NoteContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_entry", { relPath, index, expectedText }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 전문검색 (제목·본문·태그, 한국어 부분 문자열 지원). filter가 비면 전체 검색.
 */
async search(query: string, filter: SearchFilter) : Promise<Result<SearchHit[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search", { query, filter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 현재 노트를 가리키는 노트들 (백링크)
 */
async getBacklinks(relPath: string) : Promise<Result<NoteRef[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_backlinks", { relPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 백링크 + 문맥 (링크로 이어진 것과 제목만 언급한 것)
 */
async getBacklinksDetailed(relPath: string) : Promise<Result<Backlink[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_backlinks_detailed", { relPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 전체 태그와 사용 횟수
 */
async getTags() : Promise<Result<TagCount[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tags") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 태그 이름 바꾸기 / 병합 → 바뀐 노트 수.
 * `to`가 이미 쓰이는 태그면 그게 곧 병합이다.
 */
async renameTag(from: string, to: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_tag", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 템플릿 미리보기 — 오늘 날짜로 자리표시자를 채워 돌려준다.
 * 화면에서 직접 치환하지 않고 이 명령을 쓰는 이유는, 실제로 노트를 만들 때와
 * 똑같은 함수를 거쳐야 미리보기가 거짓말을 하지 않기 때문이다.
 */
async previewTemplate(content: string, title: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_template", { content, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 특정 태그가 달린 노트들
 */
async notesByTag(tag: string) : Promise<Result<NoteRef[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("notes_by_tag", { tag }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 전체 재색인 (인덱스 손상 대비 수동 명령)
 */
async reindex() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reindex") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 빠른 담기 — 한 줄을 오늘 일지의 `기록`에 붙이고 그 노트의 rel 경로를 돌려준다.
 * 
 * 앱 화면을 거치지 않고 불릴 수 있으므로(전역 단축키 → 작은 창) **여기서 스스로
 * 오늘 일지를 만든다.**
 */
async quickCapture(text: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("quick_capture", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * URL 붙여넣기용 — 페이지 제목만 가져온다. 실패·의미없는 제목이면 `Ok(None)`.
 * (편집기가 "실패하면 원본 URL을 그대로 둔다"로 처리하므로 여기서는 실패를 에러로
 * 올리지 않는다 — 에러 문구를 화면에 보여줄 자리가 없다)
 */
async fetchPageTitle(url: string) : Promise<string | null> {
    return await TAURI_INVOKE("fetch_page_title", { url });
},
/**
 * 첨부 색인 현황 (색인된 수 · 스캔본 · 암호 · 실패)
 */
async fileIndexStatus() : Promise<Result<FileIndexStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("file_index_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 첨부 색인 시작. **바로 돌려주고 백그라운드에서 추출한다** —
 * PDF 한 건이 15초까지 걸려서(실측) 커맨드가 기다리면 앱이 멈춘 것처럼 보인다.
 * 
 * 진행 상황은 `file-index-progress`, 끝나면 `file-index-done` 이벤트로 알린다.
 * 이미 추출해 둔 문서는 캐시에서 즉시 채우므로 두 번째부터는 사실상 즉시 끝난다.
 */
async buildFileIndex() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("build_file_index") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 첨부를 색인에서 뺀다 (토글 끄기). 추출 캐시는 남겨 다시 켤 때 즉시 복구한다.
 */
async dropFileIndex() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("drop_file_index") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 추출 캐시를 비우고 처음부터 다시 읽는다 (설정의 "문서 다시 읽기").
 * 깨졌던 파일이 고쳐졌거나 추출기가 개선됐을 때 쓴다.
 */
async resetFileIndex() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_file_index") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 전체 책의 기록을 엔트리 단위로 펼쳐 반환한다 (정렬·필터는 화면에서).
 */
async listEntries() : Promise<Result<ReadingEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_entries") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 데일리노트 요약. `date`는 `YYYY-MM-DD`.
 */
async dailyDigest(date: string) : Promise<Result<DailyDigest, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("daily_digest", { date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * vault 전체의 미완 할 일 (내용이 있는 `- [ ]`만). 최근 노트가 앞에 온다.
 */
async listOpenTodos(limit: number) : Promise<Result<TodoItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_open_todos", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 타입별 제목 머릿글 템플릿 조회 (쓸 수 없는 타입이면 빈 문자열)
 */
async getTitleTemplate(typeId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_title_template", { typeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 타입별 제목 머릿글 템플릿 저장
 */
async setTitleTemplate(typeId: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_title_template", { typeId, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 제목 없이 닫은 노트에 `{날짜} {본문 첫머리}`로 이름을 붙인다.
 * 이미 이름이 있거나 본문이 비었으면 아무것도 하지 않고 원래 rel을 돌려준다.
 */
async autoTitleNote(relPath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auto_title_note", { relPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * vault에서 규격에 어긋난 노트를 찾는다 (고치지는 않는다)
 */
async auditVault() : Promise<Result<NoteIssue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("audit_vault") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 점검 항목 한 건 수리 → (바뀌었을 수 있는) rel 경로
 */
async fixIssue(relPath: string, kind: IssueKind) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fix_issue", { relPath, kind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 파싱 못 하는 파일의 원문 읽기 (수리 화면 전용)
 */
async readRaw(relPath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_raw", { relPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 파일 원문 그대로 쓰기 (수리 화면 전용 — 정규화하지 않는다)
 */
async writeRaw(relPath: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_raw", { relPath, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 노트의 스냅샷 목록 (최신 우선)
 */
async listHistory(relPath: string) : Promise<Result<HistoryItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_history", { relPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 스냅샷 원문 (미리보기용)
 */
async readHistory(relPath: string, stamp: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_history", { relPath, stamp }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 해당 스냅샷으로 되돌린다 (되돌리기 직전 상태도 스냅샷으로 남는다)
 */
async restoreHistory(relPath: string, stamp: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_history", { relPath, stamp }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 스냅샷 전부 삭제 → 지운 개수
 */
async purgeHistory() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("purge_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 스냅샷 보관 정책 변경 (설정에서 호출)
 */
async setHistoryPolicy(maxPerNote: number, minIntervalSecs: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_history_policy", { maxPerNote, minIntervalSecs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 휴지통 목록
 */
async listTrash() : Promise<Result<TrashItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_trash") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 휴지통에서 노트 복구 → 복구된 rel 경로
 */
async restoreTrash(fileName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_trash", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 휴지통에서 retention_days보다 오래된 항목 영구 삭제 (0이면 안 함) → 삭제 개수
 */
async purgeTrash(retentionDays: number) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("purge_trash", { retentionDays }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 사용자 정의 분류 추가
 */
async addCustomType(label: string, fields: FieldDef[], template: string) : Promise<Result<TypeDef, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_custom_type", { label, fields, template }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 사용자 정의 분류의 본문 템플릿 수정 (생성 후에도 언제든 변경 가능)
 */
async updateCustomTypeTemplate(id: string, template: string) : Promise<Result<TypeDef, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_custom_type_template", { id, template }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 사용자 정의 분류 제거 — 내부 노트는 자유노트로 이동
 */
async removeCustomType(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_custom_type", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 노트 제목 변경 (파일명 + 링크 연쇄 수정, 책이면 독서기록도 연동) → 새 rel 경로
 */
async renameNote(relPath: string, newTitle: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_note", { relPath, newTitle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * frontmatter 일부 필드만 갱신 (목록 뷰 인라인 편집용)
 */
async updateFrontmatter(relPath: string, patch: JsonValue) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_frontmatter", { relPath, patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 이미지 파일을 책 표지로 첨부하고 frontmatter cover에 기록 → 표지 rel 경로 반환
 */
async attachCover(bookRelPath: string, srcPath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("attach_cover", { bookRelPath, srcPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 클립보드/붙여넣기 이미지를 책 표지로 저장하고 frontmatter cover 갱신 → 표지 rel 경로
 */
async attachCoverPasted(bookRelPath: string, dataBase64: string, ext: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("attach_cover_pasted", { bookRelPath, dataBase64, ext }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 외부 파일을 일반 첨부로 복사 → rel 경로 반환
 */
async importAttachment(srcPath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_attachment", { srcPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 클립보드에서 붙여넣은 이미지 저장 (base64) → rel 경로 반환
 */
async savePastedImage(dataBase64: string, ext: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_pasted_image", { dataBase64, ext }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 카카오 책 검색 API로 도서 검색. 키가 비면 내장 키를 쓰고,
 * 카카오가 실패하거나 결과가 없으면 교보 자동완성으로 폴백한다.
 */
async searchBooks(query: string, apiKey: string) : Promise<Result<BookSearchHit[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_books", { query, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * URL에서 표지 이미지를 내려받아 책에 첨부하고 frontmatter cover 갱신 → 표지 rel 경로
 */
async attachCoverFromUrl(bookRelPath: string, url: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("attach_cover_from_url", { bookRelPath, url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 부실한 책들을 카카오 책 API + 분야 추정으로 자동 보강.
 * 빈 필드만 채우고(사용자 입력 보존), API 한도(429)에 닿으면 즉시 멈춘다.
 */
async enrichBooks(apiKey: string, limit: number) : Promise<Result<EnrichReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enrich_books", { apiKey, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 교보문고에서 ISBN으로 책 메타 조회 (프론트 직접 호출용)
 */
async fetchKyoboMeta(isbn: string) : Promise<Result<KyoboMeta, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_kyobo_meta", { isbn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 제목(+저자)으로 카카오에서 첫 히트를 찾고, ISBN으로 교보 소개까지 붙여 제안 메타를 반환.
 */
async autofillBook(title: string, author: string, apiKey: string) : Promise<Result<BookMeta, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("autofill_book", { title, author, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 부실한 책들의 보강 제안을 저장하지 않고 미리 계산해 반환 (책마다 확인 모드용)
 */
async enrichPreview(apiKey: string, limit: number) : Promise<Result<EnrichPreview, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enrich_preview", { apiKey, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 미리보기 제안 한 건을 실제로 적용 (빈 필드만 채움, 표지는 URL에서 재다운로드)
 */
async enrichApplyOne(proposal: EnrichProposal) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enrich_apply_one", { proposal }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 진행 중인 일괄 자동채우기를 취소 요청한다 (다음 루프에서 중단).
 */
async cancelEnrich() : Promise<void> {
    await TAURI_INVOKE("cancel_enrich");
},
/**
 * 데일리/자유노트 본문 템플릿 읽기 (kind: "daily"|"free"). 커스텀 없으면 기본값.
 */
async getNoteTemplate(kind: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_note_template", { kind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 데일리/자유노트 본문 템플릿 저장 (빈 내용이면 기본값으로 되돌림)
 */
async setNoteTemplate(kind: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_note_template", { kind, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 미러 폴더들로 동기화 (vault 우선, 미러가 더 새로우면 충돌 보고)
 */
async mirrorSync(targets: string[]) : Promise<Result<MirrorReport[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mirror_sync", { targets }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 미러 충돌 해결: pull=true면 미러 내용을 vault로 가져오고 재색인
 */
async mirrorResolve(target: string, relPath: string, pull: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mirror_resolve", { target, relPath, pull }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * 백링크 한 건 — 어떤 노트가, 어느 대목에서 가리키는지.
 */
export type Backlink = ({ rel_path: string; note_type: string; title: string; date: string }) & { 
/**
 * 링크가 실제로 쓰인 줄들 (콜아웃 `>` 표시는 떼고 다듬은 것)
 */
contexts: string[]; 
/**
 * `[[링크]]` 없이 제목만 언급한 경우 (아직 잇지 않은 언급)
 */
unlinked: boolean }
/**
 * 수동 입력 화면에서 제안할 책 메타 (카카오 검색 + 교보 소개)
 */
export type BookMeta = { author: string; publisher: string; isbn: string; genre: string; cover_url: string; intro: string; rating: string }
/**
 * 카카오 책 검색 결과 한 건
 */
export type BookSearchHit = { title: string; authors: string; publisher: string; isbn: string; thumbnail_url: string; published: string }
/**
 * 사용자 정의 콜아웃 종류 (vault의 `_callouts.json`에 저장 — vault를 옮기면 함께 간다)
 */
export type CalloutDef = { label: string; 
/**
 * 이모지 아이콘
 */
icon: string; 
/**
 * 고정 팔레트 이름 (amber/sky/emerald/violet/rose/neutral)
 */
color: string; 
/**
 * 어디에 쓸지: "daily" | "book" | "both"
 */
scope: string }
/**
 * 데일리노트 하단 요약 바에 뿌릴 값들 (템플릿과 무관하게 항상 계산한다)
 */
export type DailyDigest = { 
/**
 * vault 전체의 미완 할 일
 */
open_todos_total: number; 
/**
 * 그 날짜 데일리노트 안의 미완 할 일
 */
open_todos_today: number; 
/**
 * 읽는 중인 책 제목 (최대 3권)
 */
reading_titles: string[]; 
/**
 * 읽는 중인 책의 rel 경로 (1권일 때 바로 열기용)
 */
reading_rels: string[]; reading_count: number; finished_total: number; finished_this_year: number; 
/**
 * 그 날짜에 기록을 남긴 책들
 */
today_entries: DigestBookEntry[]; today_entry_count: number }
/**
 * 데일리노트 빠른 입력 구분. 종류마다 들어가는 섹션과 형식이 다르다.
 */
export type DailyKind = 
/**
 * 체크박스 항목으로 `## 할 일`에 추가
 */
"todo" | 
/**
 * 콜아웃으로 `## 기록`에 추가
 */
"log" | 
/**
 * 콜아웃으로 `## 기록`에 추가
 */
"feeling"
/**
 * 그 날짜에 기록이 추가된 책 하나
 */
export type DigestBookEntry = { book_rel: string; book_title: string; count: number }
/**
 * 미리보기 결과
 */
export type EnrichPreview = { candidates: number; stopped_rate_limit: boolean; proposals: EnrichProposal[] }
/**
 * 한 권에 대한 보강 제안 (빈 필드에 채울 후보값만 담는다)
 */
export type EnrichProposal = { rel: string; title: string; cur_author: string; new_author: string; new_publisher: string; new_isbn: string; new_genre: string; new_intro: string; new_cover_url: string }
/**
 * 자동 보강 결과 보고
 */
export type EnrichReport = { 
/**
 * 처리 대상(부실한 책) 총 개수
 */
candidates: number; 
/**
 * 이번에 실제로 처리한 책 수
 */
processed: number; 
/**
 * 한 가지 이상 채워진 책 수
 */
enriched: number; filled_genre: number; filled_intro: number; filled_meta: number; 
/**
 * API 한도(429) 도달로 중단됨
 */
stopped_rate_limit: boolean; 
/**
 * 아직 처리하지 못한 남은 책 수 (한도/제한으로)
 */
remaining: number; errors: string[] }
/**
 * 독서기록 엔트리 구분 (콜아웃 이름으로 사용)
 */
export type EntryKind = "excerpt" | "thought" | "summary" | "question"
/**
 * frontmatter 필드 하나의 정의 (GUI 폼 렌더링용)
 */
export type FieldDef = { name: string; label: string; kind: FieldKind; required: boolean; 
/**
 * Select일 때 선택지 (value)
 */
options: string[]; 
/**
 * Select일 때 선택지 한글 라벨 (options와 같은 길이)
 */
option_labels: string[] }
/**
 * GUI 폼 위젯 종류
 */
export type FieldKind = "text" | "date" | "select" | "tags" | "number" | "url" | 
/**
 * 로컬 이미지 경로 또는 URL (표지 등 — GUI에서 파일 선택 지원)
 */
"image" | 
/**
 * `[[제목]]` 형태의 위키링크 문자열
 */
"wikilink"
/**
 * 첨부 색인 상태 — 화면에 "문서 48개 · 스캔본 12개 · 암호 10개"를 알리는 재료
 */
export type FileIndexStatus = { 
/**
 * 색인에 들어간 문서 수 (텍스트가 있는 것)
 */
indexed: number; 
/**
 * 텍스트가 없는 문서 — 스캔본으로 보이는 것
 */
empty: number; 
/**
 * 암호가 걸려 못 읽은 문서
 */
encrypted: number; 
/**
 * 파서가 실패한 문서
 */
failed: number; 
/**
 * 크기 상한을 넘은 문서
 */
too_big: number }
/**
 * 스냅샷 한 건
 */
export type HistoryItem = { 
/**
 * 파일명 스탬프 (복원 시 키)
 */
stamp: string; 
/**
 * 읽기 좋은 시각 "YYYY-MM-DD HH:MM"
 */
saved_at: string; 
/**
 * 그 시점 본문 글자 수 (공백 제외)
 */
char_count: number }
/**
 * 점검에서 발견한 문제의 종류. 한 파일당 하나만 보고하며, 이 열거 순서가 우선순위다.
 */
export type IssueKind = 
/**
 * 타입 폴더 밖(루트 등)에 있는 노트 — 목록에 아예 안 잡힌다
 */
"outside_type_folder" | 
/**
 * frontmatter YAML 문법 오류 — 자동으로 고칠 수 없다
 */
"parse_error" | 
/**
 * `---` 블록 자체가 없음
 */
"no_frontmatter" | 
/**
 * date 누락 또는 YYYY-MM-DD 형식 아님
 */
"missing_date" | 
/**
 * frontmatter의 type이 폴더와 다름
 */
"type_mismatch" | 
/**
 * book/writing의 status 값이 정의 밖
 */
"unknown_status"
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * 교보문고 자동완성 API로 얻은 책 메타 (없으면 빈 문자열)
 */
export type KyoboMeta = { intro: string; genre: string; cover_url: string; rating: string }
export type MirrorReport = { target: string; copied: number; skipped: number; 
/**
 * 미러 쪽이 더 새로워서 덮지 않은 파일 (rel 경로)
 */
conflicts: string[]; errors: string[] }
/**
 * 보기 화면에 그릴 블록 하나.
 * `kind`가 "callout"이면 `entry_index`로 수정·삭제할 수 있고,
 * "raw"면 외부 편집기에서 콜아웃 없이 써 넣은 원문이라 보여주기만 한다.
 */
export type NoteBlock = { kind: string; entry_index: number | null; kind_label: string; date: string; text: string; 
/**
 * raw 블록이 어느 섹션에서 왔는지 (기록 섹션 안이면 빈 문자열)
 */
section: string }
/**
 * 편집기용 노트 전체 내용
 */
export type NoteContent = { rel_path: string; note_type: string; frontmatter: JsonValue; body: string }
/**
 * 점검 항목 한 건
 */
export type NoteIssue = { rel_path: string; kind: IssueKind; label: string; 
/**
 * 무엇이 문제인지 (파일별 구체 정보)
 */
detail: string; 
/**
 * [고치기]를 누르면 무엇을 할지
 */
suggestion: string; fixable: boolean }
/**
 * 백링크/태그 조회 결과 행
 */
export type NoteRef = { rel_path: string; note_type: string; title: string; date: string }
/**
 * 사이드바/대시보드 목록용 요약 정보
 */
export type NoteSummary = { rel_path: string; note_type: string; title: string; date: string; tags: string[]; 
/**
 * 본문 글자 수 (공백 제외) — 글쓰기 진행 표시용
 */
char_count: number; 
/**
 * 독서기록(콜아웃) 엔트리 수 — 책의 기록 활동 표시용
 */
entry_count: number; 
/**
 * frontmatter 전체 (책장 뷰 등이 genre/status/cover 등을 사용)
 */
frontmatter: JsonValue }
/**
 * 일지의 할 일 한 건 (index는 문서에 적힌 순서 — 화면 정렬과 무관하게 이 값으로 조작한다)
 */
export type NoteTodo = { index: number; done: boolean; text: string }
/**
 * 책 한 권의 기록 콜아웃 한 건 (어느 책의 것인지까지 붙여 평탄화한 형태)
 */
export type ReadingEntry = { book_rel: string; book_title: string; book_author: string; 
/**
 * 책의 분야 (장르별 보기·필터용)
 */
genre: string; 
/**
 * 책에 달린 태그
 */
tags: string[]; 
/**
 * 표지 rel 경로 (없으면 빈 문자열)
 */
cover: string; kind_label: string; date: string; text: string }
/**
 * 검색 결과를 좁히는 조건. 모두 비어 있으면 필터 없음(기존 동작).
 */
export type SearchFilter = { 
/**
 * 노트 타입 id 목록 (비면 전체)
 */
types: string[]; 
/**
 * 최근 N일 이내만 (0이면 기간 제한 없음)
 */
days: number; 
/**
 * 이 태그 중 하나라도 가진 노트만 (비면 전체)
 */
tags: string[]; 
/**
 * 노트를 볼지 첨부를 볼지
 */
scope: SearchScope; 
/**
 * 오타·초성을 견디는 검색. 끄면 지금까지의 정확 검색만 한다.
 */
fuzzy: boolean; 
/**
 * 이 말이 들어간 결과는 뺀다 (제목·본문·태그 어디든).
 * 퍼지와 무관하게 **정확히** 판단한다 — 뺄 것은 확실히 빼야 한다.
 */
exclude: string[] }
export type SearchHit = { rel_path: string; note_type: string; title: string; date: string; 
/**
 * 매치 주변 본문 발췌
 */
snippet: string }
/**
 * 검색 대상. 노트와 첨부 문서를 **따로** 묻는다.
 * 
 * 같이 묻지 않는 이유: 첨부 검색은 노트 검색보다 훨씬 비싸다(거대한 본문의 발췌 생성).
 * 화면은 노트 결과를 먼저 그리고 첨부 결과를 뒤에 붙인다 — 첫 응답이 첨부 때문에
 * 늦어지지 않는다.
 */
export type SearchScope = 
/**
 * 노트만 (첨부가 색인돼 있어도 제외) — 기존 동작
 */
"Notes" | 
/**
 * 첨부 문서만
 */
"Files"
/**
 * 첫 실행 화면에 제안할 저장 위치 (클라우드 동기화 폴더 등)
 */
export type StorageDir = { label: string; path: string }
export type TagCount = { tag: string; count: number }
/**
 * 어느 노트에 있는 미완 할 일 한 줄
 */
export type TodoItem = { rel_path: string; note_type: string; note_title: string; date: string; text: string }
/**
 * 휴지통에 있는 삭제된 노트 한 건
 */
export type TrashItem = { 
/**
 * 휴지통 내 실제 파일명 (복구 시 키로 사용): `{YYYYMMDD-HHMMSS}_{원래이름}.md`
 */
file_name: string; 
/**
 * 삭제 전 원래 파일 이름 (스탬프 접두어 제거)
 */
original_name: string; 
/**
 * 삭제 시각 (읽기 좋은 형식)
 */
deleted_at: string }
/**
 * 타입 하나의 전체 정의 (내장 + 사용자 정의 공통)
 */
export type TypeDef = { 
/**
 * frontmatter `type` 값
 */
id: string; label: string; 
/**
 * vault 내 폴더 이름
 */
folder: string; fields: FieldDef[]; 
/**
 * 새 노트 본문 템플릿 ({{date}}, {{title}} 치환)
 */
template: string; builtin: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
